apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/redhat-cop/gitops-catalog/serverless-operator/operator/overlays/stable?ref=main
  - github.com/redhat-cop/gitops-catalog/serverless-operator/instance/knative-serving/overlays/default?ref=main
  - github.com/redhat-cop/gitops-catalog/serverless-operator/instance/knative-eventing/base?ref=main
  - knative-kafka.yaml
  - https://github.com/redhat-cop/gitops-catalog/rhods-operator/operator/overlays/stable?ref=main

