name: Build and push images

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: build images
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build ai-demo-upload-service
        id: build-ai-demo-upload-service
        run: docker build services/upload-service --file services/upload-service/Dockerfile -t ai-demo-upload-service:main
      - name: Push ai-demo-upload-service
        id: push-ai-demo-upload-service
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ai-demo-upload-service
          tags: main
          registry: quay.io/kevent-mesh
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Print ai-demo-upload-service image url
        run: echo "ai-demo-upload-service image pushed to ${{ steps.push-ai-demo-upload-service.outputs.registry-paths }}"

      - name: Build ai-demo-minio-webhook-source
        id: build-ai-demo-minio-webhook-source
        run: docker build services/minio-webhook-source --file services/minio-webhook-source/Dockerfile -t ai-demo-minio-webhook-source:main
      - name: Push ai-demo-minio-webhook-source
        id: push-ai-demo-minio-webhook-source
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ai-demo-minio-webhook-source
          tags: main
          registry: quay.io/kevent-mesh
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Print ai-demo-minio-webhook-source image url
        run: echo "ai-demo-minio-webhook-source image pushed to ${{ steps.push-ai-demo-minio-webhook-source.outputs.registry-paths }}"

      - name: Build ai-demo-ui-service
        id: build-ai-demo-ui-service
        run: docker build services/ui-service --file services/ui-service/Dockerfile -t ai-demo-ui-service:main
      - name: Push ai-demo-ui-service
        id: push-ai-demo-ui-service
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ai-demo-ui-service
          tags: main
          registry: quay.io/kevent-mesh
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Print ai-demo-ui-service image url
        run: echo "ai-demo-ui-service image pushed to ${{ steps.push-ai-demo-ui-service.outputs.registry-paths }}"
